server:
  port: 8464   # single entry point

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: openid, profile, email
            redirect-uri: "{baseUrl}/login/oauth2/code/google"
        provider:
          google:
            issuer-uri: https://accounts.google.com
  application:
    name: auth-gateway-service
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "${FRONTEND_ORIGINS:http://localhost:3000, https://yourfrontend.onrender.com}"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true

      routes:
        - id: user-service
          uri: ${USER_SERVICE_URL:http://localhost:8081}   # local default, override in prod
          predicates:
            - Path=/user/api/**
          filters:
            - StripPrefix=1

        - id: book-service
          uri: ${BOOK_SERVICE_URL:http://localhost:8088}   # local default, override in prod
          predicates:
            - Path=/book/api/**
          filters:
            - StripPrefix=1

jwt:
  secret: ${JWT_SECRET:mysuperlongrandomsecretmysuperlongrandomsecret1234}

user:
  service:
    url: ${USER_SERVICE_URL:http://localhost:8081}/api/users

app:
  cors:
    allowed-origins:
      - http://localhost:3000
      - https://yourfrontend.onrender.com

frontend:
  base-url: ${FRONTEND_URL:http://localhost:3000}
